set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if (DEFINED OMNI3576_SDK_ROOT)
    set(_OMNI3576_SDK_ROOT "${OMNI3576_SDK_ROOT}")
elseif (DEFINED ENV{OMNI3576_SDK_ROOT})
    set(_OMNI3576_SDK_ROOT "$ENV{OMNI3576_SDK_ROOT}")
else ()
    set(_OMNI3576_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../../Omni3576-sdk")
endif ()

get_filename_component(_OMNI3576_SDK_ROOT "${_OMNI3576_SDK_ROOT}" ABSOLUTE)
set(OMNI3576_SDK_ROOT "${_OMNI3576_SDK_ROOT}" CACHE PATH "Path to Luckfox Omni3576 SDK")

set(_RK3576_TOOLCHAIN_ROOT
    "${OMNI3576_SDK_ROOT}/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu"
)
set(_RK3576_TOOLCHAIN_BIN "${_RK3576_TOOLCHAIN_ROOT}/bin")

if (NOT EXISTS "${_RK3576_TOOLCHAIN_BIN}/aarch64-none-linux-gnu-g++")
    message(FATAL_ERROR
        "RK3576 toolchain not found. Set OMNI3576_SDK_ROOT to the Omni3576 SDK root. "
        "Current path: ${OMNI3576_SDK_ROOT}"
    )
endif ()

set(CMAKE_C_COMPILER "${_RK3576_TOOLCHAIN_BIN}/aarch64-none-linux-gnu-gcc" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "${_RK3576_TOOLCHAIN_BIN}/aarch64-none-linux-gnu-g++" CACHE FILEPATH "")
set(CMAKE_AR "${_RK3576_TOOLCHAIN_BIN}/aarch64-none-linux-gnu-ar" CACHE FILEPATH "")
set(CMAKE_RANLIB "${_RK3576_TOOLCHAIN_BIN}/aarch64-none-linux-gnu-ranlib" CACHE FILEPATH "")
set(CMAKE_STRIP "${_RK3576_TOOLCHAIN_BIN}/aarch64-none-linux-gnu-strip" CACHE FILEPATH "")

set(CMAKE_SYSROOT "${_RK3576_TOOLCHAIN_ROOT}/aarch64-none-linux-gnu/libc" CACHE PATH "")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" CACHE PATH "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
